name: Run Telegram Bot

on:
  workflow_dispatch:  # Allows manual start
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours (adjust as needed)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust as per your bot's requirements

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the bot
      - name: Run the bot
        run: |
          python bot.py
